---
title: "Metabolites report for `r unique(Product()$Name)`"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    number_sections: true
    df_print: kable 
---

`r input$comment`

```{r setup, echo=F}
knitr::opts_chunk$set(echo = TRUE)
if(!"pacman" %in% installed.packages()) install.packages("pacman")
pacman::p_load("cowplot", "readr", "gridExtra", "tinytex", "grid", "png", "rsvg")

# tinytex::install_tinytex()
```

<!-- Première page -->
```{r, echo=FALSE}

tab = Product()[sort(input$table_rows_selected), ]

myTheme <- gridExtra::ttheme_default(base_size = 6,
                        core=list(
        bg_params = list(fill=c(rep(c("grey95", "grey90"),
                                    length.out=nrow(tab)) ),
                         alpha = rep(c(1,0.5), each=5))
        ))

gridExtra::grid.table(
  tab[input$columns], rows = NULL, theme = myTheme
)

```

\newpage
```{r, echo=FALSE, fig.height=15, fig.width=10}

myTheme2 <- gridExtra::ttheme_default(base_size = 15,
                        core=list(
        bg_params = list(fill=c(rep(c("grey95", "grey90"),
                                    length.out=nrow(tab)) ),
                         alpha = rep(c(1,0.5), each=5))
        ))

for(metabo in 1:nrow(tab)){
  filename = list.files(path(), recursive = T, pattern = paste0("^", tab$Formula[metabo], "_", tab$Index[metabo], "_"))
  if(length(filename) > 1) filename = grep(ifelse(tab$Polarity[metabo]=="Positive mode", "plus", "minus"), filename, value=T)
  
  
  tabname = list.files(path(), recursive = T, pattern = paste0("table_", tab$Formula[metabo], "_", tab$Index[metabo], "_"))
  if(length(tabname) > 1) tabname = grep(tab$Polarity[metabo], tabname, value=T)
  
  if(length(tabname) == 1){
    tab_match = read_tsv(file.path(path(), tabname), col_types = cols()) 
    tab_match = tab_match[-which(tab_match$transfo == "No match"), ]
    
    if(nrow(tab_match) > 0){
      num_cols = names(Filter(is.numeric, tab_match))
      tab_match[num_cols] = apply(tab_match[num_cols], 2, function(x) round(x, 4) )
      
      # Display the figure and the table of MS2 match, if it exists
      grid.arrange(rasterGrob(readPNG(rsvg_png(file.path(path(), filename), height = 1500, width = 1500))), 
                   tableGrob(tab_match, rows=NULL, theme=myTheme2),
                   nrow=2, heights = c(10,5))
    }else{
      grid.arrange( rasterGrob(readPNG(rsvg_png(file.path(path(), filename), height = 1500, width = 1500))) )
    }
    
  }else{
    grid.arrange( rasterGrob(readPNG(rsvg_png(file.path(path(), filename), height = 1500, width = 1500))) )
  }
  
}
```
